name: gestureapp
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.3+2
  permission_handler: ^8.1.4+2
  http: ^0.13.3
  progress_loading_button: ^1.0.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth-Bold.ttf
          weight: 900
        - asset: assets/fonts/Amaranth-BoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Amaranth-Italic.ttf
          weight: 600
        - asset: assets/fonts/Amaranth-Regular.ttf
          weight: 400
  uses-material-design: true
